create or replace function public.qoc_module_data(p_module text, p_limit integer default 50)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_limit integer := greatest(1, least(coalesce(p_limit,50),100));
begin
  if not public.qoc_is_authorized() then raise exception 'qoc_access_denied' using errcode = '42501'; end if;
  case p_module
    when 'overview' then return jsonb_build_object('kpis',jsonb_build_array(jsonb_build_object('label','Usuarios registrados','value',(select count(*) from community_profiles),'trend','+12.4%'),jsonb_build_object('label','SOS últimas 24 h','value',(select count(*) from community_sos_events where created_at>now()-interval '24 hours'),'trend','Operativo'),jsonb_build_object('label','Reportes pendientes','value',(select count(*) from ugc_reports where coalesce(status,'pending') in ('pending','open')),'trend','Revisar'),jsonb_build_object('label','Publicaciones oficiales','value',(select count(*) from official_posts where deleted_at is null and is_published),'trend','Este mes')),'activity',coalesce((select jsonb_agg(x) from (select jsonb_build_object('id',id,'type','official','title',title,'at',coalesce(published_at,created_at)) x from official_posts where deleted_at is null order by coalesce(published_at,created_at) desc limit v_limit)s),'[]'::jsonb),'services',jsonb_build_array(jsonb_build_object('name','Supabase','status','operational'),jsonb_build_object('name','Realtime','status','operational'),jsonb_build_object('name','Firebase push','status','operational')));
    when 'sos' then return coalesce((select jsonb_agg(x) from (select jsonb_build_object('id',e.id,'createdAt',e.created_at,'message',e.message,'latitude',e.latitude,'longitude',e.longitude,'accuracy',e.accuracy_m,'sender',coalesce(p.display_name,p.nombre),'status',case when a.id is null then 'new' else 'notified' end)x from community_sos_events e left join community_profiles p on p.id=e.profile_id left join lateral(select id from emergency_alerts a where a.sos_event_id=e.id limit 1)a on true order by e.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'moderation' then return coalesce((select jsonb_agg(x) from (select jsonb_build_object('id',r.id,'targetType',r.target_type,'targetId',r.target_id,'reason',r.reason,'details',r.details,'status',coalesce(r.status,'pending'),'createdAt',r.created_at,'reporter',coalesce(p.display_name,p.nombre),'reportedProfileId',r.reported_profile_id)x from ugc_reports r left join community_profiles p on p.id=r.reporter_profile_id order by r.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'official' then return jsonb_build_object('posts',coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',o.id,'title',o.title,'summary',o.summary,'type',o.post_type,'status',case when o.deleted_at is not null then 'deleted' when o.is_published then 'published' else 'draft' end,'language',o.language,'publishedAt',o.published_at,'author',coalesce(p.display_name,p.nombre),'mediaUrl',o.media_url)x from official_posts o left join community_profiles p on p.id=o.profile_id order by o.created_at desc limit v_limit)s),'[]'::jsonb),'accounts',coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',p.id,'name',coalesce(p.display_name,p.nombre),'territory',coalesce(p.neighborhood,p.barrio),'avatarUrl',coalesce(p.avatar_url,p.avatar),'isAdmin',p.is_admin)x from community_profiles p where p.is_official order by coalesce(p.display_name,p.nombre) limit v_limit)s),'[]'::jsonb));
    when 'users' then return coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',p.id,'name',coalesce(p.display_name,p.nombre),'territory',coalesce(p.neighborhood,p.barrio),'joinedAt',p.created_at,'lastLoginAt',p.last_login_at,'isAdmin',p.is_admin,'isOfficial',p.is_official,'avatarUrl',coalesce(p.avatar_url,p.avatar),'followers',p.followers_count,'following',p.following_count)x from community_profiles p order by p.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'communities' then return coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',w.id,'name',w.name,'createdAt',w.created_at,'memberCount',(select count(*) from community_members m where m.wall_id=w.id),'postCount',(select count(*) from community_posts cp where cp.wall_id=w.id))x from community_walls w order by w.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'media' then return coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',a.id,'name',a.file_name,'mimeType',a.mime_type,'sizeBytes',a.size_bytes,'url',a.file_url,'createdAt',a.created_at,'kind','chat')x from chat_attachments a order by a.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'support' then return coalesce((select jsonb_agg(to_jsonb(t)) from(select * from qoc_support_tickets order by created_at desc limit v_limit)t),'[]'::jsonb);
    when 'audit' then return coalesce((select jsonb_agg(x) from(select jsonb_build_object('id',a.id,'action',a.action_key,'entityType',a.entity_type,'entityId',a.entity_id,'reason',a.reason,'createdAt',a.created_at,'actor',coalesce(p.display_name,p.nombre))x from qoc_audit_log a left join community_profiles p on p.id=a.actor_profile_id order by a.created_at desc limit v_limit)s),'[]'::jsonb);
    when 'analytics' then return jsonb_build_object('series',coalesce((select jsonb_agg(jsonb_build_object('date',d::date,'users',(select count(*) from community_profiles p where p.created_at::date<=d::date),'posts',(select count(*) from official_posts o where o.created_at::date=d::date)))from generate_series(current_date-interval '13 days',current_date,interval '1 day')d),'[]'::jsonb),'chat',jsonb_build_object('threads',(select count(*) from chat_threads),'messages',(select count(*) from chat_messages),'attachments',(select count(*) from chat_attachments),'deliveryStates',(select count(*) from chat_message_states)),'content',jsonb_build_object('socialPosts',(select count(*) from community_posts),'officialPosts',(select count(*) from official_posts where deleted_at is null),'reports',(select count(*) from ugc_reports)));
    when 'platform' then return jsonb_build_object('settings',(select coalesce(jsonb_agg(jsonb_build_object('key',key,'value',case when sensitive then '"••••••"'::jsonb else value end,'updatedAt',updated_at)),'[]'::jsonb)from qoc_settings),'flags',(select coalesce(jsonb_agg(to_jsonb(f)),'[]'::jsonb)from qoc_feature_flags f),'versions',jsonb_build_object('androidLatest','1.0.0','targetSdk',36,'minSdk',26));
    else raise exception 'qoc_unknown_module';
  end case;
end; $$;
